# SPDX-License-Identifier: MIT
# Copyright (c) 2026 EoS Project

"""EoS Boot Integrator — generates eboot-specific build inputs.

Takes validated boot.yaml and produces:
- C header with flash layout constants
- Linker script fragments for stage0/stage1
- Image packing commands
- Signing commands
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

import yaml


class EosBootIntegrator:
    """Generates eboot build inputs from validated boot config."""

    def __init__(self, output_dir: str = "_generated"):
        self.output_dir = Path(output_dir)

    def generate_from_boot_yaml(self, boot_yaml_path: str) -> Dict[str, Path]:
        """Read boot.yaml and generate all eboot integration files."""
        path = Path(boot_yaml_path)
        data = yaml.safe_load(path.read_text())
        boot = data.get("boot", data)

        self.output_dir.mkdir(parents=True, exist_ok=True)
        outputs = {}

        outputs["flash_layout_h"] = self._generate_flash_layout_h(boot)
        outputs["linker_fragment"] = self._generate_linker_fragment(boot)
        outputs["pack_script"] = self._generate_pack_script(boot)
        outputs["cmake_defs"] = self._generate_cmake_defs(boot)

        return outputs

    def _generate_flash_layout_h(self, boot: Dict[str, Any]) -> Path:
        """Generate C header with flash layout constants."""
        layout = boot.get("layout", {})
        flash_base = boot.get("flash_base", "0x08000000")
        if isinstance(flash_base, str):
            flash_base_int = int(flash_base, 16)
        else:
            flash_base_int = flash_base

        lines = [
            "/* Auto-generated by ebuild — eboot flash layout */",
            "#ifndef EBOOT_FLASH_LAYOUT_H",
            "#define EBOOT_FLASH_LAYOUT_H",
            "",
            f"#define EBOOT_FLASH_BASE        {hex(flash_base_int)}",
            f"#define EBOOT_FLASH_SIZE        {boot.get('flash_size', 0)}",
            "",
        ]

        for region_name, region in layout.items():
            name_upper = region_name.upper()
            offset = region.get("offset", "0x0")
            size = region.get("size", 0)
            if isinstance(offset, str):
                offset_int = int(offset, 16)
            else:
                offset_int = offset

            lines.append(f"#define EBOOT_{name_upper}_OFFSET  {hex(offset_int)}")
            lines.append(f"#define EBOOT_{name_upper}_ADDR    ({hex(flash_base_int)} + {hex(offset_int)})")
            lines.append(f"#define EBOOT_{name_upper}_SIZE    {size}")
            lines.append("")

        policy = boot.get("policy", {})
        lines.append(f"#define EBOOT_MAX_BOOT_ATTEMPTS {policy.get('max_boot_attempts', 3)}")
        lines.append(f"#define EBOOT_WATCHDOG_MS       {policy.get('watchdog_timeout_ms', 5000)}")
        lines.append(f"#define EBOOT_REQUIRE_SIGNATURE {1 if policy.get('require_signature') else 0}")
        lines.append(f"#define EBOOT_ANTI_ROLLBACK     {1 if policy.get('anti_rollback') else 0}")
        lines.append("")
        lines.append("#endif /* EBOOT_FLASH_LAYOUT_H */")
        lines.append("")

        path = self.output_dir / "eboot_flash_layout.h"
        path.write_text("\n".join(lines))
        return path

    def _generate_linker_fragment(self, boot: Dict[str, Any]) -> Path:
        """Generate linker script memory region fragment."""
        layout = boot.get("layout", {})
        flash_base = boot.get("flash_base", "0x08000000")
        if isinstance(flash_base, str):
            flash_base_int = int(flash_base, 16)
        else:
            flash_base_int = flash_base

        lines = [
            "/* Auto-generated by ebuild — eboot linker memory regions */",
            "MEMORY",
            "{",
        ]

        for region_name, region in layout.items():
            offset = region.get("offset", "0x0")
            size = region.get("size", 0)
            if isinstance(offset, str):
                offset_int = int(offset, 16)
            else:
                offset_int = offset

            addr = flash_base_int + offset_int
            attr = "rx" if "stage" in region_name else "rw"
            lines.append(f"    {region_name:<20s} ({attr}) : ORIGIN = {hex(addr)}, LENGTH = {size}")

        lines.extend(["}", ""])

        path = self.output_dir / "eboot_memory.ld"
        path.write_text("\n".join(lines))
        return path

    def _generate_pack_script(self, boot: Dict[str, Any]) -> Path:
        """Generate image packing shell script."""
        image = boot.get("image", {})
        hash_algo = image.get("hash_algo", "sha256")
        image.get("sign_algo", "ed25519")

        lines = [
            "#!/bin/bash",
            "# Auto-generated by ebuild — eboot image pack + sign",
            "set -e",
            "",
            "FIRMWARE=$1",
            'OUTPUT="${FIRMWARE%.bin}.signed.bin"',
            'KEY="${2:-signing_key.pem}"',
            "",
            f"echo 'Hashing firmware ({hash_algo})...'",
            f"{hash_algo}sum $FIRMWARE > ${{FIRMWARE}}.{hash_algo}",
            "",
            "echo 'Packing image header...'",
            "python3 -c \"",
            "import struct, hashlib, sys",
            "fw = open(sys.argv[1], 'rb').read()",
            f"h = hashlib.{hash_algo}(fw).digest()",
            "header = struct.pack('<4sII32s', b'EBOOT', 1, len(fw), h)",
            "out = open(sys.argv[2], 'wb')",
            "out.write(header)",
            "out.write(fw)",
            "out.close()",
            "\" $FIRMWARE $OUTPUT",
            "",
            "echo \"Packed: $OUTPUT\"",
            "",
        ]

        path = self.output_dir / "pack_image.sh"
        path.write_text("\n".join(lines))
        return path

    def _generate_cmake_defs(self, boot: Dict[str, Any]) -> Path:
        """Generate CMake definitions file for eboot build."""
        board = boot.get("board", "custom")
        layout = boot.get("layout", {})
        policy = boot.get("policy", {})

        lines = [
            "# Auto-generated by ebuild — eboot CMake definitions",
            f'set(EBLDR_BOARD "{board}")',
            f'set(EBLDR_FLASH_SIZE {boot.get("flash_size", 0)})',
            "",
        ]

        for region_name, region in layout.items():
            name_upper = region_name.upper()
            lines.append(f'set(EBLDR_{name_upper}_SIZE {region.get("size", 0)})')

        lines.append("")
        lines.append(f'set(EBLDR_MAX_BOOT_ATTEMPTS {policy.get("max_boot_attempts", 3)})')
        lines.append(f'set(EBLDR_REQUIRE_SIGNATURE {"ON" if policy.get("require_signature") else "OFF"})')
        lines.append("")

        path = self.output_dir / "eboot_config.cmake"
        path.write_text("\n".join(lines))
        return path
