# SPDX-License-Identifier: MIT
# Copyright (c) 2026 EoS Project

#!/usr/bin/env python3
"""Generate eboot C headers from validated boot.yaml config.

This script is the eboot-side contract: it takes a validated boot.yaml
(produced by ebuild) and generates deterministic C artifacts that the
eboot build consumes. No LLM logic — pure template rendering.

Usage:
    python generate_config.py boot.yaml [output_dir]
"""

import sys
import os
from pathlib import Path

import yaml


def generate_flash_layout_h(boot: dict, output_dir: Path) -> Path:
    """Generate eboot_generated_layout.h from boot config."""
    layout = boot.get("layout", {})
    flash_base = boot.get("flash_base", "0x08000000")
    flash_base_int = int(flash_base, 16) if isinstance(flash_base, str) else flash_base

    lines = [
        "/* Auto-generated by eboot/scripts/generate_config.py */",
        "/* Source: boot.yaml — DO NOT EDIT MANUALLY */",
        "#ifndef EBOOT_GENERATED_LAYOUT_H",
        "#define EBOOT_GENERATED_LAYOUT_H",
        "",
        f"#define EBOOT_FLASH_BASE         {hex(flash_base_int)}",
        f"#define EBOOT_FLASH_SIZE         {boot.get('flash_size', 0)}",
        "",
    ]

    for name, region in layout.items():
        upper = name.upper()
        offset = region.get("offset", "0x0")
        size = region.get("size", 0)
        off_int = int(offset, 16) if isinstance(offset, str) else offset

        lines.append(f"#define EBOOT_{upper}_OFFSET     {hex(off_int)}")
        lines.append(f"#define EBOOT_{upper}_ADDR       ({hex(flash_base_int)} + {hex(off_int)})")
        lines.append(f"#define EBOOT_{upper}_SIZE       {size}")
        lines.append("")

    policy = boot.get("policy", {})
    lines.append(f"#define EBOOT_MAX_BOOT_ATTEMPTS  {policy.get('max_boot_attempts', 3)}")
    lines.append(f"#define EBOOT_WATCHDOG_MS        {policy.get('watchdog_timeout_ms', 5000)}")
    lines.append(f"#define EBOOT_REQUIRE_SIGNATURE  {1 if policy.get('require_signature') else 0}")
    lines.append(f"#define EBOOT_ANTI_ROLLBACK      {1 if policy.get('anti_rollback') else 0}")

    image = boot.get("image", {})
    lines.append(f'#define EBOOT_HASH_ALGO          "{image.get("hash_algo", "sha256")}"')
    lines.append(f'#define EBOOT_SIGN_ALGO          "{image.get("sign_algo", "ed25519")}"')

    rtos = boot.get("rtos", {})
    if rtos:
        lines.append("")
        lines.append("/* RTOS boot parameters */")
        lines.append(f'#define EBOOT_RTOS_TYPE          "{rtos.get("type", "baremetal")}"')
        lines.append(f'#define EBOOT_MPU_MODE           "{rtos.get("mpu_mode", "protected")}"')
        lines.append(f"#define EBOOT_RTOS_TICK_HZ       {rtos.get('tick_rate_hz', 1000)}")
        lines.append(f"#define EBOOT_RTOS_PRIORITIES    {rtos.get('num_priorities', 8)}")

    lines.extend(["", "#endif /* EBOOT_GENERATED_LAYOUT_H */", ""])

    path = output_dir / "eboot_generated_layout.h"
    path.write_text("\n".join(lines))
    return path


def generate_linker_defs(boot: dict, output_dir: Path) -> Path:
    """Generate linker script memory definitions."""
    layout = boot.get("layout", {})
    flash_base = boot.get("flash_base", "0x08000000")
    flash_base_int = int(flash_base, 16) if isinstance(flash_base, str) else flash_base

    lines = [
        "/* Auto-generated by eboot/scripts/generate_config.py */",
        "MEMORY",
        "{",
    ]

    for name, region in layout.items():
        offset = region.get("offset", "0x0")
        size = region.get("size", 0)
        off_int = int(offset, 16) if isinstance(offset, str) else offset
        addr = flash_base_int + off_int
        attr = "rx" if "stage" in name else "rw"
        lines.append(f"    {name:<24s} ({attr}) : ORIGIN = {hex(addr)}, LENGTH = {size}")

    lines.extend(["}", ""])

    path = output_dir / "eboot_generated_memory.ld"
    path.write_text("\n".join(lines))
    return path


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <boot.yaml> [output_dir]")
        sys.exit(1)

    boot_yaml = Path(sys.argv[1])
    output_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("generated")
    output_dir.mkdir(parents=True, exist_ok=True)

    data = yaml.safe_load(boot_yaml.read_text())
    boot = data.get("boot", data)

    h_path = generate_flash_layout_h(boot, output_dir)
    ld_path = generate_linker_defs(boot, output_dir)

    print(f"Generated: {h_path}")
    print(f"Generated: {ld_path}")


if __name__ == "__main__":
    main()
